In [1]:
!git status

On branch form-ui
Your branch is up to date with 'origin/form-ui'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app.py
	modified:   templates/form.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.ipynb_checkpoints/
	__pycache__/

no changes added to commit (use "git add" and/or "git commit -a")

In [2]:
!ls

 app.py  'pandas demo.ipynb'   README.md	  templates
 data	  __pycache__	       requirements.txt

In [1]:
import pandas as pd

In [2]:
ball_df = pd.read_csv('data/IPL Ball-by-Ball 2008-2020.csv')
match_df = pd.read_csv('data/IPL Matches 2008-2020.csv')

In [21]:
ball_df['batsman'].unique()

array(['RT Ponting', 'BB McCullum', 'DJ Hussey', 'Mohammad Hafeez',
       'SC Ganguly', 'CL White', 'MV Boucher', 'B Akhil', 'AA Noffke',
       'P Kumar', 'Z Khan', 'SB Joshi', 'W Jaffer', 'JH Kallis',
       'R Dravid', 'V Kohli', 'K Goel', 'MEK Hussey', 'JR Hopes',
       'SK Raina', 'JDP Oram', 'S Badrinath', 'PA Patel', 'ML Hayden',
       'MS Dhoni', 'KC Sangakkara', 'Yuvraj Singh', 'SM Katich',
       'IK Pathan', 'T Kohli', 'YK Pathan', 'S Dhawan', 'G Gambhir',
       'SK Warne', 'D Salunkhe', 'SK Trivedi', 'V Sehwag', 'SR Watson',
       'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'S Chanderpaul',
       'LRPL Taylor', 'WP Saha', 'AS Yadav', 'A Symonds', 'SB Bangar',
       'WPUJC Vaas', 'RP Singh', 'AC Gilchrist', 'Y Venugopal Rao',
       'VVS Laxman', 'RG Sharma', 'SB Styris', 'LR Shukla', 'PP Chawla',
       'Kamran Akmal', 'DPMD Jayawardene', 'S Sohal', 'B Lee', 'WA Mota',
       'Shahid Afridi', 'DJ Bravo', 'A Nehra', 'MA Khote', 'GC Smith',
       'Pankaj Singh', 'S Sreesanth', 'VRV Singh', 'SS Tiwary',
       'RR Sarwan', 'DS Kulkarni', 'R Vinay Kumar', 'M Kartik',
       'I Sharma', 'AB Agarkar', 'AM Rahane', 'TM Srivastava',
       'Shoaib Malik', 'MK Tiwary', 'KD Karthik', 'R Bhatia',
       'MF Maharoof', 'VY Mahesh', 'B Chipli', 'DW Steyn', 'DB Das',
       'MK Pandey', 'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna',
       'SE Marsh', 'SA Asnodkar', 'BJ Hodge', 'Sohail Tanvir',
       'Salman Butt', 'Umar Gul', 'AB Dinda', 'AB de Villiers',
       'SP Fleming', 'S Vidyut', 'JA Morkel', 'LPC Silva', 'DB Ravi Teja',
       'Misbah-ul-Haq', 'PJ Sangwan', 'YV Takawale', 'RR Raje',
       'Mohammad Asif', 'GD McGrath', 'Joginder Sharma', 'MS Gony',
       'M Muralitharan', 'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha',
       'MM Patel', 'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar',
       'PP Ojha', 'SP Goswami', 'SR Tendulkar', 'U Kaul', 'Niraj Patel',
       'AD Mascarenhas', 'TM Dilshan', 'A Mishra', 'LA Pomersbach',
       'Iqbal Abdulla', 'Younis Khan', 'PM Sarvesh Kumar',
       'DP Vijaykumar', 'Shoaib Akhtar', 'Abdur Razzak', 'H Das',
       'DR Smith', 'SD Chitnis', 'CRD Fernando', 'VS Yeligati',
       'L Balaji', 'A Mukund', 'RR Powar', 'JP Duminy', 'A Flintoff',
       'T Thushara', 'KP Pietersen', 'JD Ryder', 'T Henderson',
       'Kamran Khan', 'RS Bopara', 'MC Henriques', 'CH Gayle',
       'R Bishnoi', 'KV Sharma', 'FH Edwards', 'AS Raut', 'PC Valthaty',
       'RJ Quiney', 'Yashpal Singh', 'M Manhas', 'AA Bilakhia',
       'AN Ghosh', 'BAW Mendis', 'DL Vettori', 'MN van Wyk',
       'RE van der Merwe', 'TL Suman', 'Shoaib Ahmed', 'GR Napier',
       'KP Appanna', 'LA Carseldine', 'NV Ojha', 'SM Harwood', 'M Vijay',
       'DA Warner', 'SB Jakati', 'RJ Harris', 'D du Preez', 'M Morkel',
       'AD Mathews', 'SL Malinga', 'C Nanda', 'J Botha',
       'Mashrafe Mortaza', 'A Singh', 'GJ Bailey', 'AB McDonald',
       'Y Nagar', 'SS Shaikh', 'R Ashwin', 'Mohammad Ashraful',
       'Jaskaran Singh', 'Anirudh Singh', 'CA Pujara', 'OA Shah',
       'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'YA Abdulla',
       'EJG Morgan', 'JM Kemp', 'S Tyagi', 'RS Gavaskar', 'SE Bond',
       'S Ladda', 'DP Nannes', 'KA Pollard', 'DR Martyn', 'S Narwal',
       'MJ Lumb', 'Bipul Sharma', 'AB Barath', 'FY Fazal', 'AC Voges',
       'MD Mishra', 'UT Yadav', 'J Theron', 'SJ Srivastava', 'R Sharma',
       'Mandeep Singh', 'KM Jadhav', 'SW Tait', 'KB Arun Karthik',
       'KAJ Roach', 'PD Collingwood', 'CK Langeveldt', 'VS Malik',
       'A Mithun', 'AP Dole', 'AN Ahmed', 'RS Sodhi', 'DE Bollinger',
       'S Sriram', 'B Sumanth', 'C Madan', 'AG Paunikar', 'MR Marsh',
       'AJ Finch', 'STR Binny', 'Harmeet Singh', 'IR Jaggi',
       'DT Christian', 'MA Agarwal', 'RV Gomez', 'AUK Pathan',
       'UBT Chand', 'DJ Jacobs', 'NJ Rimmington', 'Sunny Singh',
       'AL Menaria', 'WD Parnell', 'JJ van der Wath', 'R Ninan',
       'S Aravind', 'MS Wade', 'TD Paine', 'JEC Franklin', 'SB Wagh',
       'AC Thomas', 'Shakib Al Hasan', 'DH Yagnik', 'S Randiv',
       'BJ Haddin', 'NLTC Perera', 'NL McCullum', 'JE Taylor',
       'J Syed Mohammad', 'RN ten Doeschate', 'TR Birt', 'AG Murtaza',
       'Harpreet Singh', 'M Klinger', 'AC Blizzard', 'I Malhotra',
       'L Ablish', 'CA Ingram', 'S Nadeem', 'P Parameswaran',
       'CJ Ferguson', 'VR Aaron', 'AA Chavan', 'ND Doshi', 'B Kumar',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'F du Plessis',
       'RE Levi', 'GJ Maxwell', 'SPD Smith', 'SA Yadav', 'MN Samuels',
       'KK Cooper', 'JP Faulkner', 'HV Patel', 'DAJ Bracewell',
       'DJ Harris', 'Ankit Sharma', 'SP Narine', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'DA Miller', 'Azhar Mahmood', 'P Negi',
       'RJ Peterson', 'KMDN Kulasekara', 'A Ashish Reddy',
       'V Pratap Singh', 'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh',
       'AP Majumdar', 'PA Reddy', 'K Upadhyay', 'P Awana', 'AD Russell',
       'A Chandila', 'CA Lynn', 'Sunny Gupta', 'MC Juneja', 'KK Nair',
       'GH Vihari', 'R Shukla', 'MDKJ Perera', 'AS Rajpoot', 'B Laughlin',
       'M Vohra', 'JD Unadkat', 'Mohammed Shami', 'BMAJ Mendis',
       'R Rampaul', 'CH Morris', 'SV Samson', 'SMSM Senanayake',
       'BJ Rohrer', 'KL Rahul', 'Q de Kock', 'R Dhawan', 'MG Johnson',
       'LJ Wright', 'IC Pandey', 'CM Gautam', 'X Thalaivan Sargunam',
       'DJG Sammy', 'KW Richardson', 'MM Sharma', 'UA Birla',
       'Parvez Rasool', 'Sandeep Sharma', 'S Kaul', 'Sachin Baby',
       'PV Tambe', 'NM Coulter-Nile', 'CJ Anderson', 'NJ Maddinson',
       'AR Patel', 'JJ Bumrah', 'JDS Neesham', 'TG Southee', 'MA Starc',
       'BR Dunk', 'RR Rossouw', 'Shivam Sharma', 'YS Chahal',
       'LMP Simmons', 'VH Zol', 'Imran Tahir', 'BCJ Cutting',
       'BE Hendricks', 'S Gopal', 'M de Lange', 'R Tewatia', 'JO Holder',
       'Karanveer Singh', 'SS Iyer', 'DJ Hooda', 'Anureet Singh',
       'KS Williamson', 'SA Abbott', 'J Suchith', 'RG More', 'D Wiese',
       'HH Pandya', 'SN Khan', 'MJ McClenaghan', 'DJ Muthuswami',
       'PJ Cummins', 'SN Thakur', 'JC Buttler', 'CR Brathwaite',
       'MP Stoinis', 'Ishan Kishan', 'C Munro', 'P Sahu', 'KH Pandya',
       'AD Nath', 'MJ Guptill', 'KJ Abbott', 'TM Head', 'M Ashwin',
       'NS Naik', 'RR Pant', 'SW Billings', 'KC Cariappa',
       'PSP Handscomb', 'Swapnil Singh', 'J Yadav', 'UT Khawaja',
       'HM Amla', 'F Behardien', 'A Zampa', 'BB Sran', 'N Rana',
       'S Kaushik', 'ER Dwivedi', 'CJ Jordan', 'A Choudhary', 'TS Mills',
       'BA Stokes', 'JJ Roy', 'Vishnu Vinod', 'Basil Thampi', 'CR Woakes',
       'RA Tripathi', 'DL Chahar', 'V Shankar', 'Rashid Khan',
       'LH Ferguson', 'RD Chahar', 'C de Grandhomme', 'AF Milne',
       'S Badree', 'Mohammad Nabi', 'AJ Tye', 'K Rabada', 'Kuldeep Yadav',
       'Washington Sundar', 'DM Bravo', 'AR Bawne', 'SP Jackson',
       'Ankit Soni', 'TA Boult', 'E Lewis', 'MA Wood', 'RK Singh',
       'DJM Short', 'K Gowtham', 'TK Curran', 'M Markande', 'B Stanlake',
       'Mujeeb Ur Rahman', 'A Dananjaya', 'Shivam Mavi', 'Shubman Gill',
       'Mohammed Siraj', 'H Klaasen', 'RK Bhui', 'JC Archer', 'PP Shaw',
       'LE Plunkett', 'Mustafizur Rahman', 'AD Hales', 'MK Lomror',
       'DR Shorey', 'MM Ali', 'M Prasidh Krishna', 'P Chopra',
       'JPR Scantlebury-Searles', 'Abhishek Sharma', 'IS Sodhi',
       'SO Hetmyer', 'S Dube', 'NA Saini', 'JM Bairstow', 'Rasikh Salam',
       'KMA Paul', 'N Pooran', 'P Ray Barman', 'S Lamichhane',
       'SM Curran', 'GC Viljoen', 'Avesh Khan', 'HF Gurney', 'SD Lad',
       'AS Joseph', 'MJ Santner', 'R Parag', 'JL Denly', 'LS Livingstone',
       'KK Ahmed', 'AJ Turner', 'SE Rutherford', 'Harpreet Brar',
       'Y Prithvi Raj', 'P Simran Singh', 'JL Pattinson', 'A Nortje',
       'T Banton', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad',
       'TU Deshpande', 'Abdul Samad', 'PK Garg', 'JR Philippe',
       'Kartik Tyagi', 'CV Varun', 'KL Nagarkoti', 'I Udana',
       'Ravi Bishnoi', 'Shahbaz Ahmed', 'AT Carey', 'N Jagadeesan',
       'T Natarajan', 'P Dubey', 'SS Cottrell', 'Arshdeep Singh',
       'DR Sams'], dtype=object)

In [4]:
pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 50)

In [6]:
filt = (ball_df['id'] == 392221) & \
    (ball_df['batsman'] == 'BB McCullum') & \
    (pd.notna(ball_df['extras_type']))
res = ball_df.loc[filt]
res.head(30)

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
22507,392221,1,19,2,BB McCullum,WP Saha,JH Kallis,4,1,5,0,0,NaN,NaN,NaN,noballs,Kolkata Knight Riders,Royal Challengers Bangalore
22508,392221,1,19,3,BB McCullum,WP Saha,JH Kallis,0,1,1,0,0,NaN,NaN,NaN,noballs,Kolkata Knight Riders,Royal Challengers Bangalore
22576,392221,1,10,5,BB McCullum,DJ Hussey,JD Ryder,0,4,4,0,0,NaN,NaN,NaN,byes,Kolkata Knight Riders,Royal Challengers Bangalore

In [7]:
ball_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193468 entries, 0 to 193467
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                193468 non-null  int64
 1   inning            193468 non-null  int64
 2   over              193468 non-null  int64
 3   ball              193468 non-null  int64
 4   batsman           193468 non-null  object
 5   non_striker       193468 non-null  object
 6   bowler            193468 non-null  object
 7   batsman_runs      193468 non-null  int64
 8   extra_runs        193468 non-null  int64
 9   total_runs        193468 non-null  int64
 10  non_boundary      193468 non-null  int64
 11  is_wicket         193468 non-null  int64
 12  dismissal_kind    9495 non-null    object
 13  player_dismissed  9495 non-null    object
 14  fielder           6784 non-null    object
 15  extras_type       10233 non-null   object
 16  batting_team      193468 non-null  object
 17  bowling_team      193277 non-null  object
dtypes: int64(9), object(9)
memory usage: 26.6+ MB

In [8]:
match_df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [17]:
filt = ball_df['batsman'].str.contains('morris', na=False)

In [21]:
morris = ball_df.loc[filt]

In [22]:
morris

Empty DataFrame
Columns: [id, inning, over, ball, batsman, non_striker, bowler, batsman_runs, extra_runs, total_runs, non_boundary, is_wicket, dismissal_kind, player_dismissed, fielder, extras_type, batting_team, bowling_team]
Index: []

In [11]:
filt = (ball_df['batsman'] == 'BB McCullum') \
& (ball_df['bowling_team'] == 'Royal Challengers Bangalore') \
& ((ball_df['extras_type'] == 'noballs') | ((pd.isna(ball_df['extras_type']))))

In [12]:
batsmanAgainstTeam = ball_df.loc[filt]

In [13]:
batsmanAgainstTeam

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
5,335982,1,7,4,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
7,335982,1,7,6,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143614,1082621,2,1,2,BB McCullum,Ishan Kishan,S Aravind,0,0,0,0,0,NaN,NaN,NaN,NaN,Gujarat Lions,Royal Challengers Bangalore
143615,1082621,2,1,3,BB McCullum,Ishan Kishan,S Aravind,1,0,1,0,0,NaN,NaN,NaN,NaN,Gujarat Lions,Royal Challengers Bangalore
143619,1082621,2,2,1,BB McCullum,Ishan Kishan,S Badree,1,0,1,0,0,NaN,NaN,NaN,NaN,Gujarat Lions,Royal Challengers Bangalore
143626,1082621,2,3,2,BB McCullum,SK Raina,S Aravind,1,0,1,0,0,NaN,NaN,NaN,NaN,Gujarat Lions,Royal Challengers Bangalore
143633,1082621,2,4,1,BB McCullum,SK Raina,S Badree,0,0,0,0,1,caught,BB McCullum,AB de Villiers,NaN,Gujarat Lions,Royal Challengers Bangalore

In [14]:
merge_result = batsmanAgainstTeam.merge(match_df, how='inner', on='id')

In [15]:
res = merge_result.groupby(
        ['id']
    ).agg(
        batman = ('batsman', 'unique'),
        team_playing = ('batting_team', 'unique'),
        against = ('bowling_team', 'unique'),
        runs = ('batsman_runs', 'sum'),
        balls = ('ball', 'count'),     
        date = ('date', 'unique'),
        city = ('city', 'unique'),
        venue = ('venue', 'unique')
    )

In [16]:
merge_result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 501 entries, 0 to 500
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                501 non-null    int64
 1   inning            501 non-null    int64
 2   over              501 non-null    int64
 3   ball              501 non-null    int64
 4   batsman           501 non-null    object
 5   non_striker       501 non-null    object
 6   bowler            501 non-null    object
 7   batsman_runs      501 non-null    int64
 8   extra_runs        501 non-null    int64
 9   total_runs        501 non-null    int64
 10  non_boundary      501 non-null    int64
 11  is_wicket         501 non-null    int64
 12  dismissal_kind    26 non-null     object
 13  player_dismissed  26 non-null     object
 14  fielder           19 non-null     object
 15  extras_type       4 non-null      object
 16  batting_team      501 non-null    object
 17  bowling_team      501 non-null    object
 18  city              496 non-null    object
 19  date              501 non-null    object
 20  player_of_match   501 non-null    object
 21  venue             501 non-null    object
 22  neutral_venue     501 non-null    int64
 23  team1             501 non-null    object
 24  team2             501 non-null    object
 25  toss_winner       501 non-null    object
 26  toss_decision     501 non-null    object
 27  winner            501 non-null    object
 28  result            501 non-null    object
 29  result_margin     493 non-null    float64
 30  eliminator        501 non-null    object
 31  method            0 non-null      object
 32  umpire1           501 non-null    object
 33  umpire2           501 non-null    object
dtypes: float64(1), int64(10), object(23)
memory usage: 153.2+ KB

In [16]:
res

,batman,team_playing,against,runs,balls,date,city,venue
id,,,,,,,,
335982,[BB McCullum],[Kolkata Knight Riders],[Royal Challengers Bangalore],158,71,[2008-04-18],[Bangalore],[M Chinnaswamy Stadium]
392199,[BB McCullum],[Kolkata Knight Riders],[Royal Challengers Bangalore],0,1,[2009-04-29],[Durban],[Kingsmead]
392221,[BB McCullum],[Kolkata Knight Riders],[Royal Challengers Bangalore],84,63,[2009-05-12],[Centurion],[SuperSport Park]
419148,[BB McCullum],[Kolkata Knight Riders],[Royal Challengers Bangalore],45,36,[2010-04-10],[Bangalore],[M Chinnaswamy Stadium]
501200,[BB McCullum],[Kochi Tuskers Kerala],[Royal Challengers Bangalore],45,31,[2011-04-09],[Kochi],[Nehru Stadium]
501247,[BB McCullum],[Kochi Tuskers Kerala],[Royal Challengers Bangalore],22,16,[2011-05-08],[Bangalore],[M Chinnaswamy Stadium]
548344,[BB McCullum],[Kolkata Knight Riders],[Royal Challengers Bangalore],43,37,[2012-04-28],[Kolkata],[Eden Gardens]
734013,[BB McCullum],[Chennai Super Kings],[Royal Challengers Bangalore],19,13,[2014-05-18],[Ranchi],[JSCA International Stadium Complex]
829745,[BB McCullum],[Chennai Super Kings],[Royal Challengers Bangalore],4,5,[2015-04-22],[Bangalore],[M Chinnaswamy Stadium]
829779,[BB McCullum],[Chennai Super Kings],[Royal Challengers Bangalore],20,15,[2015-05-04],[Chennai],"[MA Chidambaram Stadium, Chepauk]"
980937,[BB McCullum],[Gujarat Lions],[Royal Challengers Bangalore],42,23,[2016-04-24],[Rajkot],[Saurashtra Cricket Association Stadium]
980987,[BB McCullum],[Gujarat Lions],[Royal Challengers Bangalore],11,12,[2016-05-14],[Bangalore],[M Chinnaswamy Stadium]
981013,[BB McCullum],[Gujarat Lions],[Royal Challengers Bangalore],1,4,[2016-05-24],[Bangalore],[M Chinnaswamy Stadium]
1082610,[BB McCullum],[Gujarat Lions],[Royal Challengers Bangalore],72,44,[2017-04-18],[Rajkot],[Saurashtra Cricket Association Stadium]
1082621,[BB McCullum],[Gujarat Lions],[Royal Challengers Bangalore],3,6,[2017-04-27],[Bangalore],[M Chinnaswamy Stadium]